### PR TITLE
Blog Complete; Blog add/remove tag complete; BG Color change complete

### PR DESCRIPTION
**Pull request by ded-possum**
This is a consolidated PR for tickets:
App Background Color #19
Blog Details #25
Add Tag to Blog #30
View Blog Tags #31
Remove Tag from Blog #32

### CODE REVIEW

**Review by Pstyne — APPROVED** [review]
Looks good. Didn't run into any issues! 🧁 Tasty!

**Comment by helloamandaball** [comment]
- App Background Color #19: 🟨  when selecting 2) Dark Blue, the menu automatically pops up after selection, where other colors choices have the "press any key to continue..." message.

- Blog Details #25: ✅ good
- Add Tag to Blog #30:  ✅ good
- View Blog Tags #31: ✅ good
- Remove Tag from Blog #32: ✅ good

**Review by Pstyne — APPROVED** [review]

**Comment by helloamandaball** [comment]
🍪 works great!

**Comment by ded-possum** [comment]
WAFFLES

**Pull request merged**
